# Netlify CMS settings
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  
publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /uploads
logo_url: /assets/Logo.svg
  
media_library:
  name: cloudinary
  config:
    cloud_name: committed-bodies
    api_key: 724142698475225
      
collections:

  - name: "siteConfig"
    label: "Site Settings"
    files:
    - label: "Settings"
      name: "siteSettings"  
      file: "/src/lib/data/siteSettings.json"
      fields:
        - label: "Site Settings"
          name: "config"
          widget: "object"
          collapsed: true
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
            - label: "Slogan"
              name: "slogan"
              widget: "string"
            - label: "About"
              name: "about"
              widget: "text"
    - label: "Footer"
      name: "footer"  
      file: "/src/lib/data/footer.json"
      
      fields:
        - label: "Footer Links Column 1"
          name: "footerLinks1"
          widget: "object"
          collapsed: true
          fields:
            - {label: "Column Title", name: "columnTitle", widget: "string", default: "Start Now"}
            - label: "Links"
              name: "links"
              widget: "list"
              summary: '{{fields.title}}'
              fields:
                - {label: Title, name: title, widget: string, default: "Link text"}
                - {label: Url, name: url, widget: string, default: "/"}
        - label: "Footer Links Column 2"
          name: "footerLinks2"
          widget: "object"
          collapsed: true
          fields:
            - {label: "Column Title", name: "columnTitle", widget: "string", default: "Not sure?"}
            - label: "Links"
              name: "links"
              widget: "list"
              summary: '{{fields.title}}'
              fields:
                - {label: Title, name: title, widget: string, default: "Link text"}
                - {label: Url, name: url, widget: string, default: "/"}

  - name: "blog"
    label: "Blog"
    folder: "/src/routes/blog" # The path to the folder where our blog posts are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: “Categories”, name: “categories”, widget: “select”, options: ["Transformation Stories", “Events”, “Advice”, “News”, “Announcements”, “Tutorials”]}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  
  - name: "team"
    label: "Team"
    folder: "/src/routes/team"
    create: true
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Profile Pic", name: "thumbnail", widget: "image"}
      - {label: "About", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "team"}
  
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home Page"
      name: "homePage"
      file: "/src/lib/data/homePage.json"
      fields:
      - label: "Video"
        name: "video"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Button Text"
            name: "buttonText"
            widget: "string"
          - label: "Button Link"
            name: "buttonLink"
            widget: "string"
          - label: "Video URL"
            name: "videoUrl"
            widget: "string"
      - label: "Intro"
        name: "intro"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Subtitle"
            name: "subtitle"
            widget: "string"
          - label: "Text"
            name: "text"
            widget: "text"
          - label: "Button Text"
            name: "buttonText"
            widget: "string"
          - label: "Button Link"
            name: "buttonLink"
            widget: "string"
    - label: "Facilitiy Page"
      name: "facilitypage"
      file: "/src/lib/data/facility.json"
      fields:
        - label: "Page Intro"
          name: "intro"
          widget: "object"
          collapsed: true
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
            - label: "Subtitle"
              name: "subtitle"
              widget: "string"
            - label: "Content"
              name: "content"
              widget: "text"
        - label: "Facility Features"
          name: "facilityFeatures"
          widget: "list"
          summary: '{{fields.title}}'
          fields:
            - {label: "Unique ID Number", name: "id", widget: "number"}
            - {label: "Title", name: "title", widget: "string", default: "Title for this facility feature"}
            - {label: "Name", name: "name", widget: "string", default: "Emmet"}
            - {label: "Image", name: "image", widget: "image", default: "https://scontent.fdur7-1.fna.fbcdn.net/v/t1.6435-9/55713719_310473159632468_5149878363015348224_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=8bfeb9&_nc_ohc=reATQcCDbigAX_oSpHN&_nc_ht=scontent.fdur7-1.fna&oh=00_AT9eByjzvm-S1U4wZXplxeyG1aW5wvzoN-9zffFKZywrkw&oe=6202DB7C"}
            - {label: "Content", name: "content", widget: "text", default: "Describe this feature - how does it help your clients?"}
      # Donavan
    - label: "Contact Page"
      name: "contactpage"
      file: "/src/lib/data/contactPage.json"
      fields:
        - label: "Page Intro"
          name: "intro"
          widget: "object"
          collapsed: true
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
            - label: "Subtitle"
              name: "subtitle"
              widget: "string"
            - label: "Content"
              name: "content"
              widget: "text"
        - label: "Contact Details"
          name: "contacts"
          widget: "object"
          collapsed: true
            - label: "phone"
              name: "phone"
              widget: "string"
            - label: "email"
              name: "email"
              widget: "string"
            - label: "address"
              name: "address"
              widget: "string"
            - label: "mapLink"
              name: "mapLink"
              widget: "string"
        - label: "Social Links"
          name: "socials"
          widget: "list"
          collapsed: true
          summary: '{{fields.title}}'
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Link", name: "link", widget: "string"}
    - label: "Membership Pages"
      name: "membershippages"
      file: "/src/lib/data/membershipPage.json"
      fields:
        - label: "Join Page Intro"
          name: "introJoin"
          widget: "object"
          collapsed: true
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
            - label: "Subtitle"
              name: "subtitle"
              widget: "string"
            - label: "Content"
              name: "content"
              widget: "text"
        - label: "Portal Page Intro"
          name: "introPortal"
          widget: "object"
          collapsed: true
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
            - label: "Subtitle"
              name: "subtitle"
              widget: "string"
            - label: "Content"
              name: "content"
              widget: "text"                  
        - label: "Schedule Page Intro"
          name: "introSchedule"
          widget: "object"
          collapsed: true
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
            - label: "Subtitle"
              name: "subtitle"
              widget: "string"
            - label: "Content"
              name: "content"
              widget: "text"   
        - label: "Download Page Intro"
          name: "introDownload"
          widget: "object"
          collapsed: true
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
            - label: "Subtitle"
              name: "subtitle"
              widget: "string"
            - label: "Content"
              name: "content"
              widget: "text"         