# Netlify CMS settings
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  
publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /uploads
logo_url: /assets/Logo.svg
  
media_library:
  name: cloudinary
  config:
    cloud_name: committed-bodies
    api_key: 724142698475225
      
collections:

  - name: "siteConfig"
    label: "Site Settings"
    files:
    - label: "Settings"
      name: "siteSettings"  
      file: "/src/lib/data/siteSettings.json"
      fields:
        - label: "Site Settings"
          name: "config"
          widget: "object"
          collapsed: true
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
            - label: "Slogan"
              name: "slogan"
              widget: "string"
            - label: "About"
              name: "about"
              widget: "text"
    - label: "Footer"
      name: "footer"  
      file: "/src/lib/data/footer.json"
      
      fields:
        - label: "Footer Links Column 1"
          name: "footerLinks1"
          widget: "object"
          collapsed: true
          fields:
            - {label: "Column Title", name: "columnTitle", widget: "string", default: "Start Now"}
            - label: "Links"
              name: "links"
              widget: "list"
              summary: '{{fields.title}}'
              fields:
                - {label: Title, name: title, widget: string, default: "Link text"}
                - {label: Url, name: url, widget: string, default: "/"}
        - label: "Footer Links Column 2"
          name: "footerLinks2"
          widget: "object"
          collapsed: true
          fields:
            - {label: "Column Title", name: "columnTitle", widget: "string", default: "Not sure?"}
            - label: "Links"
              name: "links"
              widget: "list"
              summary: '{{fields.title}}'
              fields:
                - {label: Title, name: title, widget: string, default: "Link text"}
                - {label: Url, name: url, widget: string, default: "/"}
# Home page collection
  - name: "homepage"
    label: "Home Page"
    files:
    - label: "Home Page"
      name: "homePage"
      file: "/src/lib/data/homePage.json"
      fields:
      - label: "Video"
        name: "video"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Button Text"
            name: "buttonText"
            widget: "string"
          - label: "Button Link"
            name: "buttonLink"
            widget: "string"
          - label: "Video URL"
            name: "videoUrl"
            widget: "string"
      - label: "Intro"
        name: "intro"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Subtitle"
            name: "subtitle"
            widget: "string"
          - label: "Text"
            name: "text"
            widget: "text"
          - label: "Button Text"
            name: "buttonText"
            widget: "string"
          - label: "Button Link"
            name: "buttonLink"
            widget: "string"
# Blog page      
  - name: "blog"
    label: "Blog Posts"
    folder: "/src/routes/blog" # The path to the folder where our blog posts are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Transformation", "Events", "Advice", "News", "Announcements", "Tutorials"]
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Body", name: "body", widget: "markdown"}
# Team members
  - name: "teamMembers"
    label: "Team Members"
    folder: "/src/routes/team"
    create: true
    identifier_field: fullName
    fields:
      - {label: "First Name", name: "firstName", widget: "string"}
      - {label: "Full Name", name: "fullName", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Group"
        name: "group"
        widget: "select"
        options: ["Trainers", "Personnel"]
      - {label: "Profile Pic", name: "thumbnail", widget: "image"}
      - label: "Specialisations"
        name: "specialisations"
        widget: "list"
        summary: '{{fields.title}}'
        fields:
          - {label: "Title", name: "title", widget: "string", default: "Eg. Nutrition"}
      - {label: "Blurb", name: "blurb", widget: "text"}
      - {label: "Action Heading", name: "actionHeading", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Action Instruction", name: "actionInstruction", widget: "text"}
      - {label: "Action Link", name: "actionLink", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "team"}
      - {label: "Bio", name: "body", widget: "markdown"}
#Team page collection
  - name: "teampage"
    label: "Team Page"
    files:
    - label: "Team Page"
      name: "teampage"
      file: "/src/lib/data/teamPage.json"
      fields:
        - label: "Team Page Intro"
          name: "intro"
          widget: "object"
          collapsed: true
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
            - label: "Subtitle"
              name: "subtitle"
              widget: "string"
            - label: "Content"
              name: "content"
              widget: "text"
# Services posts
  - name: "services"
      label: "Services"
      folder: "/src/routes/services"
      create: true
      identifier_field: fullName
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Service Pic", name: "thumbnail", widget: "image"}
        - {label: "Price", name: "price", widget: "string"}
        - {label: "Order", name: "order", widget: "number"}
        - {label: "Blurb", name: "blurb", widget: "text"}
        - {label: "Action Heading", name: "actionHeading", widget: "string"}
        - {label: "Action Instruction", name: "actionInstruction", widget: "text"}
        - {label: "Action Link", name: "actionLink", widget: "string"}
        - {label: "Action Button Text", name: "actionButtonText", widget: "string"}
        - {label: "Layout", name: "layout", widget: "hidden", default: "service"}
        - {label: "Service Description", name: "body", widget: "markdown"}
#Services page collection
  - name: "servicespage"
    label: "Services Page"
    files:
    - label: "Services Pages"
      name: "servicespage"
      file: "/src/lib/data/servicesPage.json"
      fields:
        - label: "Service Page Intro"
          name: "intro"
          widget: "object"
          collapsed: true
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
            - label: "Subtitle"
              name: "subtitle"
              widget: "string"
            - label: "Content"
              name: "content"
              widget: "text"
  