# Netlify CMS settings
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  
publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /uploads
logo_url: /assets/Logo.svg
  
media_library:
  name: cloudinary
  config:
    cloud_name: committed-bodies
    api_key: 724142698475225
      
collections:

  - name: "siteConfig"
    label: "Site Settings"
    files:
    - label: "Settings"
      name: "siteSettings"  
      file: "/src/lib/data/siteSettings.json"
      fields:
        - label: "Site Settings"
          name: "config"
          widget: "object"
          collapsed: true
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
            - label: "Slogan"
              name: "slogan"
              widget: "string"
            - label: "About"
              name: "about"
              widget: "text"
    - label: "Footer"
      name: "footer"  
      file: "/src/lib/data/footer.json"
      
      fields:
        - label: "Footer Links Column 1"
          name: "footerLinks1"
          widget: "object"
          collapsed: true
          fields:
            - {label: "Column Title", name: "columnTitle", widget: "string", default: "Start Now"}
            - label: "Links"
              name: "links"
              widget: "list"
              summary: '{{fields.title}}'
              fields:
                - {label: Title, name: title, widget: string, default: "Link text"}
                - {label: Url, name: url, widget: string, default: "/"}
        - label: "Footer Links Column 2"
          name: "footerLinks2"
          widget: "object"
          collapsed: true
          fields:
            - {label: "Column Title", name: "columnTitle", widget: "string", default: "Not sure?"}
            - label: "Links"
              name: "links"
              widget: "list"
              summary: '{{fields.title}}'
              fields:
                - {label: Title, name: title, widget: string, default: "Link text"}
                - {label: Url, name: url, widget: string, default: "/"}
         